//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bookstore1pf
{
    using System;
    using System.Collections.Generic;
    
    public partial class Books
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Books()
        {
            this.Order_composition = new HashSet<Order_composition>();
            this.Genres = new HashSet<Genres>();
        }
    
        public int id { get; set; }
        public string title { get; set; }
        public Nullable<int> author_id { get; set; }
        public Nullable<int> publishing_house_id { get; set; }
        public Nullable<System.DateTime> publication_date { get; set; }
        public string image_Path { get; set; }
        public string bookDescription { get; set; }
        public int Price { get; set; }
    
        public virtual Authors Authors { get; set; }
        public virtual Publishing_houses Publishing_houses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_composition> Order_composition { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Genres> Genres { get; set; }
    }
}
