//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bookstore1pf
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int id { get; set; }
        public Nullable<int> roleId { get; set; }
        public string userLogin { get; set; }
        public string userPassword { get; set; }
    
        public virtual Customers Customers { get; set; }
        public virtual Roles Roles { get; set; }
    }
}
